package radixcore.core;

import net.minecraftforge.fml.common.ModMetadata;
import radixcore.modules.net.AbstractPacketHandler;
import radixcore.modules.updates.IUpdateProtocol;

public final class ModMetadataEx extends ModMetadata
{
	public IUpdateProtocol updateProtocol;
	public String curseId;
	public AbstractPacketHandler packetHandler;
	
	public static ModMetadataEx getFromModMetadata(ModMetadata modData)
	{
		ModMetadataEx exData = new ModMetadataEx();
		
		exData.authorList 	 = modData.authorList;
		exData.autogenerated = modData.autogenerated;
		exData.childMods 	 = modData.childMods;
		exData.credits 		 = modData.credits;
		exData.dependants 	 = modData.dependants;
		exData.dependencies  = modData.dependencies;
		exData.description 	 = modData.description;
		exData.logoFile 	 = modData.logoFile;
		exData.modId 		 = modData.modId;
		exData.name 		 = modData.name;
		exData.parent 		 = modData.parent;
		exData.parentMod 	 = modData.parentMod;
		exData.requiredMods  = modData.requiredMods;
		exData.screenshots 	 = modData.screenshots;
		exData.url 			 = modData.url;
		exData.version 		 = modData.version;
		
		return exData;
	}
}
